### ISSUE TITLE
KeyError: 'tools' even with default pinecone as vectordb

### ISSUE THREAD

**Issue by My3VM** [aurelio-labs/arxiv-bot#2]
Traceback (most recent call last):
  File "/Volumes/Data/arxiv-bot-main/botsy.py", line 5, in <module>
    bot = arxiv_bot.manager.bots.Arxiver(
  File "/Volumes/Data/arxiv-bot-main/arxiv_bot/manager/bots.py", line 106, in __init__
    self._init_chatbot(verbose=verbose)
  File "/Volumes/Data/arxiv-bot-main/arxiv_bot/manager/bots.py", line 187, in _init_chatbot
    self.agent = langchain.agents.initialize_agent(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/initialize.py", line 64, in initialize_agent
    return AgentExecutor.from_agent_and_tools(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py", line 587, in from_agent_and_tools
    return cls(
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1064, in pydantic.main.validate_model
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py", line 595, in validate_tools
    tools = values["tools"]
KeyError: 'tools'

**Comment by My3VM** [comment]
This and many few issues related to duckdb were all due to the lowest version of frameworks. Upgrading python to 3.11 and related updates to langchain resolved this case.
